name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dc: [ldc-latest, dmd-latest]
        include:
          - os: ubuntu-latest
            dc: gdc

    steps:
    - uses: actions/checkout@v2

    - name: Install D compiler
      if: matrix.dc == 'ldc-latest' || matrix.dc == 'dmd-latest'
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: Install GDC
      if: matrix.dc == 'gdc'
      run: |
        sudo apt install gdc
        wget https://github.com/dlang/dub/releases/download/v1.23.0/dub-v1.23.0-linux-x86_64.tar.gz
        tar xvf dub-v1.23.0-linux-x86_64.tar.gz

    - name: 'Build & Test'
      run: |
        export PATH=$PATH:`pwd` # for GDC build
        # Build the project, with its main file included, without unittests
        dub build
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        dub test
