name: Create package & upload artifact(s)
inputs:
  arch:
    required: true
  os:
    required: false
    default: '' # native
  cross_target_triple:
    required: false
    default: ''
runs:
  using: composite
  steps:

    - name: Set DMD environment variable
      shell: bash
      run: |
        set -eux
        cd ..
        if [[ '${{ inputs.cross_target_triple }}' != '' ]]; then
          DMD="$PWD/bootstrap-ldc/bin/ldmd2"
        else
          DMD="$PWD/installed/bin/ldmd2"
        fi
        echo "DMD=$DMD" >> $GITHUB_ENV

    - name: Build & copy OpenD tools and libraries
      shell: bash
      run: |
        set -eux
        cd libraries
        DFLAGS= LFLAGS= ldmd2 -Iupstream -i extractor.d # need to run natively so dont use the cross compiler
        ./extractor build ../../installed/import

        cd ../opend
        $DMD -ofopend -i opend.d -I../../installed/import/
        cp opend ../../installed/bin/

    - name: Build & copy upstream dlang tools
      shell: bash
      run: |
        set -eux
        cd ..
        git clone --recursive https://github.com/dlang/tools.git dlang-tools
        cd dlang-tools
        git checkout "$(cat ../opend/ldc/packaging/dlang-tools_version)"

        mkdir bin
        $DMD -w -de -dip1000 ddemangle.d -of=bin/ddemangle
        # $DMD -w -de -dip1000 DustMite/dustmite.d DustMite/splitter.d DustMite/polyhash.d -of=bin/dustmite
        cp bin/ddemangle ../installed/bin/

    - name: 'Windows: Pack libs for cross compile'
      if: runner.os == 'Windows' && inputs.os == ''
      shell: bash
      run: |
        set -eux
        git clean -dffx
        cd ..
        artifactName="opend-latest-xpack-win64"
        tar -cJf $artifactName.tar.xz --exclude-vcs --owner=0 --group=0 --transform="s,^installed,$artifactName," installed/lib installed/bin/*.dll

    - name: Pack installation dir
      shell: bash
      run: |
        set -euxo pipefail
        cd ..
        mkdir artifacts

        if [[ '${{ github.ref }}' = refs/tags/v* ]]; then
          artifactID='${{ github.ref }}'
          artifactID="${artifactID:11}"
        else
          artifactID="latest"
        fi

        mv opend-latest-xpack-emscripten.tar.xz artifacts || true
        mv opend-latest-xpack-win64.tar.xz artifacts || true

        os='${{ inputs.os }}'
        if [[ "$os" == '' ]]; then
          if [[ '${{ runner.os }}' == Linux ]]; then
            os=linux
          elif [[ '${{ runner.os }}' == macOS ]]; then
            os=osx
          elif [[ '${{ runner.os }}' == Windows ]]; then
            os=windows
          else
            echo "Error: unknown OS '${{ runner.os }}'"
            exit 1
          fi
        fi

        artifactName="opend-$artifactID-$os-${{ inputs.arch }}"
        mv installed $artifactName || (sleep 5 && (mv installed $artifactName || (sleep 10 && mv installed $artifactName)))
        if [[ '${{ runner.os }}' == Windows ]]; then
          7z a -mx=9 artifacts/$artifactName.7z $artifactName >/dev/null
        else
          chmod -R go=rX $artifactName
          if [[ '${{ runner.os }}' == macOS ]]; then
            sudo chown -R root:wheel $artifactName
            tar -cf - $artifactName | 7za a artifacts/$artifactName.tar.xz -si -txz -mx9
          else
            tar -cf - --owner=0 --group=0 $artifactName | 7za a artifacts/$artifactName.tar.xz -si -txz -mx9
          fi
        fi

        # export ARTIFACT_{ID,NAME}
        echo "ARTIFACT_ID=$artifactID" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=$os-${{ inputs.arch }}" >> $GITHUB_ENV

    - name: 'Move artifacts dir for uploading'
      shell: bash
      run: mv ../artifacts ./

    - name: Upload artifact(s)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: artifacts/
        compression-level: 0
