#!/usr/bin/env bash

set -euo pipefail

PARSE_SCRIPT=$1
DRUNTIME_CFG_DIR=$2
TAGGED_COPY_LIST_FILE=$3
TAGS=$4
IMPDIR=$5
DST_DIR=$6

TAGGED_SRCS_FILE=${DST_DIR}/GEN_SRCS
TAGGED_COPY_FILE=${DST_DIR}/GEN_COPY

${PARSE_SCRIPT} ${DRUNTIME_CFG_DIR} ${TAGGED_SRCS_FILE} ${TAGGED_COPY_LIST_FILE} ${TAGGED_COPY_FILE} ${TAGS} ${IMPDIR}

#~ rm -f ${TAGGED_SRCS_FILE}
#~ rm -f ${TAGGED_COPY_FILE}
