# Documentation: https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 3
  round: down
  range: "80...100"

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project: true
    patch: true
    changes: true

comment: false
